version: '3.8'
services:
  db:
    image: postgres:15.2
    container_name: pruebas_unitarias_11
    restart: always
    volumes:
      - ./db/1schema.sql:/docker-entrypoint-initdb.d/1schema.sql
      - ./db/2data.sql:/docker-entrypoint-initdb.d/2data.sql
    environment:
      - POSTGRES_DB=veterinaria
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=cezl123
    ports:
      - "5432:5432"
